alerting:
  channels:
    email:
      enabled: true
      from_email: ''
      password: ''
      smtp_port: 587
      smtp_server: ''
      to_email: ''
      username: ''
    slack:
      channel: '#security-alerts'
      enabled: false
      webhook_url: ''
  enabled: true
aws:
  default_region: us-east-1
  max_events_per_service: 1000
  services:
  - ec2
  - s3
  - iam
  - cloudtrail
  - guardduty
azure:
  max_events_per_service: 1000
  services:
  - storage
  - vm
  - keyvault
  - security_center
  - activity_log
  subscription_id: ''
detection:
  rule_engine:
    chunk_size: 100
    threads: 4
gcp:
  max_events_per_service: 1000
  project_id: ''
  services:
  - iam
  - storage
  - compute
  - logging
  - security_command_center
  - asset_inventory
